<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>Lontrium.Notifier</AssemblyName>
    <RootNamespace>Lontrium.Notifier</RootNamespace>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RestoreSources>https://api.nuget.org/v3/index.json</RestoreSources>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.22621.2428" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
